export default function ItineraryPanel({ itinerary }) {
  if (!itinerary) return null

  return (
    <div className="glass-panel p-6 rounded-2xl col-span-1 lg:col-span-2 space-y-4">
      <div className="flex items-center justify-between border-b border-slate-800 pb-3">
        <div className="flex items-center gap-2">
          <span className="text-xl">📍</span>
          <div>
            <h2 className="text-base font-bold text-slate-100">Synthesized Agentic Itinerary</h2>
            <p className="text-xs text-slate-400">Generated by Itinerary Synthesizer Agent</p>
          </div>
        </div>
        <span className="text-xs px-3 py-1 rounded-full bg-purple-500/10 text-purple-300 border border-purple-500/20 font-mono">
          Final Output
        </span>
      </div>

      <div className="bg-slate-900/80 p-5 rounded-xl border border-slate-800 text-slate-200 text-sm leading-relaxed whitespace-pre-wrap font-sans">
        {itinerary.summary}
      </div>
    </div>
  )
}